### ISSUE TITLE
Unicode support & different delimiters

### ISSUE THREAD

**Issue by pjrandewijk** [luketainton/TeamsUserEnroller#10]
It would be nice if this script also support Unicode.

Import-Csv support both of these flags. It should be easy to pass them through from Add-TeamMembers to Import-Csv

**Comment by luketainton** [comment]
Hi @pjrandewijk!

Would I be correct in assuming the flags you mean are `-Delimiter` and `-Encoding`?

**Comment by luketainton** [comment]
Version 2.2.0 is available at https://www.powershellgallery.com/packages/TeamsUserEnroller/2.2.0

**Comment by pjrandewijk** [comment]
@luketainton Thank you very much. Sorry for the late reply. It seems my notifications is configured incorrectly. Yes, it is those two parameters you mentioned, are `-Delimiter` and `-Encoding?`

**Comment by luketainton** [comment]
@pjrandewijk You're welcome 😄 

Please let me know if you have any issues v2.2.0/v2.2.1 (which I released to include auto-updating), or if you have any more suggestions.

**Comment by pjrandewijk** [comment]
How do you call the function?

`Import-TeamsUsers -File C:\<path to csv file> -Encoding Unicode -Delimiter ";"`

**Comment by luketainton** [comment]
> How do you call the function?

Try this:
`Import-TeamsUsers -File C:\<path to csv file> -Encoding 'Unicode' -Delimiter ';'`

I think the `-Encoding` flag takes a string literal so it might need to be wrapped in single quotes.

**Comment by pjrandewijk** [comment]
I think I still maybe have the old version. How do I upgrade/update to the newer one. I get the following error message:

```
Import-TeamsUsers : A parameter cannot be found that matches parameter name 'Encoding'.
At line:1 char:64
+ ... sUsers -File C:\Users\petra\Downloads\62700-E20.csv -Encoding 'Unicod ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Import-TeamsUsers], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Import-TeamsUsers
```

**Comment by luketainton** [comment]
Should be able to update with `Update-Module -Name TeamsUserEnroller -RequiredVersion 2.2.1 -Force`

**Comment by pjrandewijk** [comment]
Hmmm, now I get:

```
WARNING: The version '1.1.4' of module 'MicrosoftTeams' is currently in use. Retry the operation after closing the
applications.
```
I have quit PowerShell and Quit Teams, but to no avail. There should be an easier way without rebooting though...

**Comment by luketainton** [comment]
This is usually because the module is loaded, so this might do the trick:

```powershell
Remove-Module -Name TeamsUserEnroller
Remove-Module -Name MicrosoftTeams
Update-Module -Name TeamsUserEnroller -RequiredVersion 2.2.1 -Force
```

**Comment by pjrandewijk** [comment]
Hmmm, no joy.

```PS C:\Users\petra> Remove-Module -Name TeamsUserEnroller
Remove-Module : No modules were removed. Verify that the specification of modules to remove is correct and those
modules exist in the runspace.
At line:1 char:1
+ Remove-Module -Name TeamsUserEnroller
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Remove-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Microsoft.PowerShell.Commands.RemoveModuleCommand

PS C:\Users\petra> Remove-Module -Name MicrosoftTeams
Remove-Module : No modules were removed. Verify that the specification of modules to remove is correct and those
modules exist in the runspace.
At line:1 char:1
+ Remove-Module -Name MicrosoftTeams
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Remove-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Microsoft.PowerShell.Commands.RemoveModuleCommand

PS C:\Users\petra> Update-Module -Name TeamsUserEnroller -RequiredVersion 2.2.1 -Force
WARNING: The version '1.1.4' of module 'MicrosoftTeams' is currently in use. Retry the operation after closing the
applications.```

I can't install because MicrosoftTeams is in use. But I also cannot uninstall MicrosoftTeams.

**Comment by luketainton** [comment]
Maybe `Remove` -> `Uninstall` might work:

```powershell
Uninstall-Module -Name TeamsUserEnroller
Uninstall-Module -Name MicrosoftTeams
Update-Module -Name TeamsUserEnroller -RequiredVersion 2.2.1 -Force
```
