### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by matthewblabey** [luketainton/TeamsUserEnroller#2]
Due to the world working from home, a GUI would be nice for first time users of Microsoft teams so they can easily add people into their team with ease.

**Comment by luketainton** [comment]
Cannot implement this as of yet due to Office 365 OAuth permissions. Alternative could be to have the web server execute Powershell on the backend, but this will require Windows or PS Docker container.

**Comment by luketainton** [comment]
> Cannot implement this as of yet due to Office 365 OAuth permissions. Alternative could be to have the web server execute Powershell on the backend, but this will require Windows or PS Docker container.

This is not a good idea. It would require the app to 'know' the user's O365 password which is a major security problem.
