### ISSUE TITLE
Auto provision apps

### ISSUE THREAD

**Issue by MrLyallCSIT** [luketainton/TeamsUserEnroller#6]
It would be great if the script auto-provisionned apps in the team such as Insights or Teacher Dashboard.

**Comment by luketainton** [comment]
Functionality not currently available in upstream module.

**Comment by luketainton** [comment]
Preview version 1.0.22 includes the `Add-TeamsAppInstallation` command which might do this.

**Comment by luketainton** [comment]
This is REDMINE-ISSUE-1
